/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/self.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/self.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.649, 1.789, 0.02]}>
        <primitive object={nodes.Bone}  />
      </group>
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[-0.649, 1.789, 0.02]} />
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[-0.618, 3.431, -0.267]} rotation={[0.903, 0, -Math.PI / 2]} scale={[-0.057, -0.009, -0.057]} />
      <group position={[0.272, 3.472, 0.253]} rotation={[-1.926, -1.549, -Math.PI / 2]} scale={-0.003}>
        <mesh geometry={nodes.Cube004.geometry} material={materials['Glasses handle']} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials['Glasses rim']} />
        <mesh geometry={nodes.Cube004_2.geometry} material={materials.Glasses} />
      </group>
    </group>
  )
}

useGLTF.preload('/self.glb')
